# Generated by Django 4.2.5 on 2023-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('pin', models.PositiveBigIntegerField()),
                ('state', models.CharField(max_length=80)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=80)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('myfile', models.FileField(upload_to='docs')),
            ],
        ),
    ]
