# Generated by Django 4.2.5 on 2023-09-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_rename_myfile_candidate_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='locality',
        ),
    ]
